.OBJDIR= ${.CURDIR}/obj

PROGS= \
	e01-01_hello \
	e01-03_f2c \
	e01-04_c2f \
	e01-06_0or1 \
	e01-07_EOFvalue \
	e01-08_countbtn \
	e01-09_blankreplace \
	e01-10_tbsreplace \
	e01-11_wordcount \
	e01-12_wordline \
	e01-13_wordlengthhisthor \
	e01-13_wordlengthhistvert \
	e01-14_charfreqhist \
	e01-15_f2c \
	e01-16_longestline \
	e01-17_longerline \
	e01-18_rmblanks \
	e01-19_reverse \
	e01-20_detab \
	e01_countarray \
	e01_countchar \
	e01_countline \
	e01_filecp

all: $(PROGS)

clean:
	rm -f *.core ${PROGS}

.include <bsd.prog.mk>
